### PR TITLE
WIP test: add CI tests for analog

### PR DESCRIPTION
**Pull request by brandonroberts**
Adds CI tests for AnalogJS

### CODE REVIEW

**Comment by dominikg** [comment]
i noticed you don't have  `packageManager: "yarn@version"` in your root package.json. is it possible for you to add that so that corepack knows which one to use?

**Comment by brandonroberts** [comment]
Yep, I can do that.

**Comment by brandonroberts** [comment]
Updated the packageManager, still getting the error locally

**Comment by dominikg** [comment]
are you still using yarn@1 ? 

I vaguely remember yarn v1 having problems with esbuild, eg https://github.com/evanw/esbuild/issues/1434

i think calling `yarn set version stable` and using v3 would be an improvement over that but would recommend pnpm instead. It's used a lot in the vite, vue and svelte ecosystems and the reception is very positive.

**Comment by dominikg** [comment]
@brandonroberts  any updates on this?

**Comment by brandonroberts** [comment]
Still investigating build issues (Not Vite related) with migrating. Will reopen when ready

**Pull request closed without merging**
