### PR TITLE
chore: let all suites be selected

### PR DESCRIPTION
**Pull request by patak-dev**
I don't think we should disallow the selection of paused suites.

### CODE REVIEW

**Comment by bluwy** [comment]
Would they run correctly? It looks like the current script doesn't allow `_` prefixed tests to run as well:

https://github.com/vitejs/vite-ecosystem-ci/blob/9fccb45311c724158a07b3c88336de9866248fc3/ecosystem-ci.ts#L149-L169

Otherwise I think this is a good idea, and we can allow selecting to test them explicitly. Only during the normal "run all suites" flow where we disable them by default.

**Comment by patak-dev** [comment]
Ah, you are right. I removed the `_` prefix from them and added back hydrogen as a commented suite in the general tests.

**Comment by dominikg** [comment]
when you run it on the cli it executes them too now. so there is no simple way to exclude these there anymore. the case for not selecting a specific suite on the cli is rare but it would be good if we found a way that caters both cli and gh actions

**Comment by patak-dev** [comment]
Ah, sorry I didn't wait for you here @dominikg. I forgot about the CLI, I see now why you added the `_`. Should we add a flag in the test? `export const paused = true;` ? Or `paused: true` in the test definition?

**Comment by dominikg** [comment]
we could just remove the "all" case from the cli, running them all sequentially takes ages so locally you are much more likely to focus one or some suite by actively giving their names. :thinking:  don't spend too much time on this rn, the cli is used much less than gh action so merging this first was ok, we should just clean up the cli thing at some point

**Comment by patak-dev** [comment]
That is a good point, I have never used `all` in the CLI.

**Review by lilpoozie2005 — APPROVED** [review]

**Pull request merged**
