### PR TITLE
feat: add Nx to the tests

### PR DESCRIPTION
**Pull request by mandarini**
Add Nx to the `vite-ecosystem-ci`. What this PR intends is to see if the Nx executors still work with the latest build of `vite`.

### CODE REVIEW

**Comment by dominikg** [comment]
I had already checked out the branch and would love to avoid rebasing multiple times, so please don't force push.

**Comment by mandarini** [comment]
Ooops sorry! No more changes on my end!

**Comment by dominikg** [comment]
you can add more commits and use regular push and i'll be able to merge just fine on my end. just force push  would "force" me to go back to zero first.

**Comment by dominikg** [comment]
i have added the build command, however running this locally with `pnpm test nx` fails when it is executed:
```sh
/home/dominikg/develop/vitejs/vite-ecosystem-ci/workspace/nx/nx $> yarn run build
yarn run v1.22.19
$ nx run-many --target build --all --parallel 8 --exclude nx-dev,typedoc-theme

 >  NX   The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
```

if ` --parallel 8` is using 8 parallel threads, this might not work great for github ci that runs with 3 threads for linux nodes iirc. 

@mandarini  do you think a `build:ci` or `build:ecosystem-ci` script could be added that accounts for github action runners and successfully builds the local nx version? 

I'm still a bit confused how the build script itself can start with `nx`, do you have that installed globally on your build environment or rely on a previous version downloaded from the registry?

**Comment by mandarini** [comment]
Thanks @dominikg !

I will add a new script, yes! Hm, well, the script either calls `nx` through `npx` or relies on the local version of `nx`, installed with the repository, it's in the repo's dependencies. So, I think this should be it... When we run the tests on ci, we publish a temp version of nx, and then it uses that!

**Pull request closed without merging**
