### PR TITLE
feat: add qwik city

### PR DESCRIPTION
**Pull request by patak-dev**
Discussed with @mhevery and @manucorporat about having Qwik City tested through vite-ecosystem-ci. Qwik City and their Vite plugin are part of the Qwik monorepo, so as an initial approach, I'm using `build` and the general `test`. If it takes too much time, we could only run the tests from the Qwik City package (and also the ones in the plugin?).

### CODE REVIEW

**Comment by bluwy** [comment]
The audit fail should be fixed in `main` now.

**Comment by dominikg** [comment]
Had a qwik look, but unfortunately running `pnpm test qwik` did not work for me locally.

First issue was that qwik uses a pinned rollup version in devDependencies that leads to a type inconsistency for Plugin https://github.com/BuilderIO/qwik/blob/4147d52e979f76ccf763f83135d03d009e5f92e7/package.json#L89  vs vite https://github.com/vitejs/vite/blob/0cfd26c5058fe1642b80dbc530a0e7796d05f271/packages/vite/package.json#L65

After adding and override to use "^2.79.1" in qwik

```ts
import { runInRepo } from '../utils'
import { RunOptions } from '../types'

export async function test(options: RunOptions) {
	await runInRepo({
		...options,
		overrides:{
			"rollup":"^2.79.1"
		},
		repo: 'BuilderIO/qwik',
		build: 'build',
		test: 'test'
	})
}
```

i now get a build error mentioning `yarn api.update` but it doesn't tell me which api that would be or if that's expected. 
I'm lacking the time and expertise to check out qwik build process in more detail and would appreciate if someone from qwik can take a look. @mhevery  @manucorporat :eyes:

```
qwik ❯ yarn build
(node:10674) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10674) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, transformSource
🌎 Qwik v0.12.0-dev20221022102852 [node v18.11.0, linux/x64]
/home/dominikg/develop/vitejs/vite-ecosystem-ci/workspace/qwik/qwik/packages/qwik/dist
🐷 generated package.json
🐨 build
🐮 jsx-runtime
🦁 testing
📠 cli
🐸 qwikloader: { original: '1.8kb', brotli: '926b' }
🦊 core.mjs: { original: '244.1kb', brotli: '43.5kb' }
🐭 core.min.mjs: { original: '53kb', brotli: '18.3kb' }
🐹 optimizer
🐰 server
🦉 native binding / wasm (copied from npm v0.12.0-dev20221021220048)
vite v3.2.0-beta.3 building for lib...
✓ 14 modules transformed.
../lib/index.qwik.mjs   16.52 KiB / gzip: 4.75 KiB
../lib/index.qwik.cjs   17.53 KiB / gzip: 4.99 KiB
🏙  qwik-city

❌ Use "yarn api.update" to automatically update the .md files if the api changes were expected
 Error: Use "yarn api.update" to automatically update the .md files if the api changes were expected
    at panic (file:///home/dominikg/develop/vitejs/vite-ecosystem-ci/workspace/qwik/qwik/scripts/util.ts:210:4)
    at createTypesApi (file:///home/dominikg/develop/vitejs/vite-ecosystem-ci/workspace/qwik/qwik/scripts/api.ts:133:5)
    at apiExtractor (file:///home/dominikg/develop/vitejs/vite-ecosystem-ci/workspace/qwik/qwik/scripts/api.ts:96:3)
    at build (file:///home/dominikg/develop/vitejs/vite-ecosystem-ci/workspace/qwik/qwik/scripts/build.ts:82:7)
on  main [!] via  v18.11.0 via 🦀 took 28s 
qwik ❯ 
```

Please also check your rollup devDependency, ideally that would be in sync with vite, although we might have to add an automatic override to vite-ecosystem-ci for the upcoming switch to rollup@3 in vite-4, cc @patak-dev @sapphi-red

**Comment by manucorporat** [comment]
We use api-extractor to detect changes in our public API, it's sort of a bundler for types + comparision... this error is not necessary bad, just means the public API changed, i guess some rollup type is leaking to the public API, going to look at it!

**Comment by manucorporat** [comment]
test.vite could be a thing too, let me do some checking

**Comment by manucorporat** [comment]
What does the test should do? build an app with vite?

**Comment by patak-dev** [comment]
@manucorporat there were errors before merging Rollup 3 support to Vite main, that is what dominikg was describing. Now there may be more errors as you say, for example, type errors.

About what the test should do, we don't need a new app, but probably running your regular CI tests for your vite plugin and QwikCity. Ideally, we would run `test` wholesale. For example, the [laravel](https://github.com/vitejs/vite-ecosystem-ci/blob/main/tests/laravel.ts) integration runs the regular `build` then `test`. 
Sometimes projects add a new `test:vite-ci` command when running the whole CI doesn't make sense. For example, [astro](https://github.com/vitejs/vite-ecosystem-ci/blob/main/tests/astro.ts) here does it to avoid testing create-astro and every subpackage because it is time-consuming, so [they only run their core CI](https://github.com/withastro/astro/blob/main/package.json#L23).

**Comment by dominikg** [comment]
> What does the test should do? build an app with vite?

Run as much of qwik ci as possible that depends on vite. unit tests using vite exports, e2e tests using vite dev, preview or build.
Anything that could break when vite changes

**Comment by manucorporat** [comment]
We are about to merge this:
https://github.com/BuilderIO/qwik/pull/2349

adding a couple of new scripts: `build.vite` and `test.vite`

**Comment by dominikg** [comment]
hope you don't mind i resolved the conflicts and update the tests to your latest changes in qwik repo.

**Pull request merged**
