### PR TITLE
feat: hydrogen

### PR DESCRIPTION
**Pull request by Aslemammad**
Not ready yet, WIP.

### CODE REVIEW

**Comment by patak-dev** [comment]
@Aslemammad looks good, why did you think this is WIP? ping @frandiox :)

**Review by patak-dev — APPROVED** [review]

**Comment by Aslemammad** [comment]
@patak-dev it doesn't work properly in local; I'm trying to get it working!

**Comment by Aslemammad** [comment]
@dominikg @patak-dev  do we need to migrate hydrogen to `pnpm`?

cc @frandiox

**Comment by patak-dev** [comment]
It shouldnt be needed to migrate to pnpm to add it here

**Comment by Aslemammad** [comment]
Ok, in local i've got problem with installing playwright-chromium!
I'd like to see if @frandiox agrees with merging this!

**Comment by dominikg** [comment]
i had no issues running the testsuite with ` pnpm test -- hydrogen --release 2.8.0-beta.5` but there have been failed tests.

**Comment by dominikg** [comment]
update, i'm getting an error with local vite `pnpm test hydrogen`

> error An unexpected error occurred: "ENOENT: no such file or directory, stat '/home/dominikg/develop/vite-ecosystem-ci/workspace/hydrogen/hydrogen/node_modules/vite/node_modules/resolve'".

**Comment by frandiox** [comment]
@Aslemammad Thanks a lot for driving this!

Just one thing, the command `test` only runs the unit tests. I've added a new `test:vite-ci` script that should also run e2e so please use that.

>@dominikg update, i'm getting an error with local vite `pnpm test hydrogen`

Hmm, we have all tests passing with 2.8.0-beta.5 in [this branch](https://github.com/Shopify/hydrogen/pull/414). Perhaps related to yarn vs pnpm?

**Comment by Aslemammad** [comment]
@frandiox Done!

**Comment by Aslemammad** [comment]
@frandiox @dominikg I guess our part is done here, and if you agree, we can merge this and work on the hydrogen end!

**Comment by patak-dev** [comment]
Awesome to have Hydrogen connected! Thanks @Aslemammad @frandiox 🙌🏼

**Comment by Aslemammad** [comment]
@patak-dev Thanks for the merge! We're happy too!

**Comment by dominikg** [comment]
good to see this merged :+1:  

I'm still seeing errors when running `pnpm test -- hydrogen --release 2.8.2` so maybe something still needs to be fixed on their end?
After we're confident it's working it will need to be added to the lists in our actions
https://github.com/vitejs/vite-ecosystem-ci/blob/main/.github/workflows/ecosystem-ci.yml#L36
https://github.com/vitejs/vite-ecosystem-ci/blob/main/.github/workflows/ecosystem-ci-selected.yml#L31

**Comment by Aslemammad** [comment]
@dominikg Thanks, we'll look into it with @frandiox if he wants!

**Comment by frandiox** [comment]
I can try to test locally soon. `pnpm` is just the driver in this repo but it later uses Yarn for Hydrogen, right?

**Comment by dominikg** [comment]
yes, it uses https://github.com/antfu/ni  to run with the package manager of the project (pnpm, npm, yarn)

**Comment by frandiox** [comment]
@dominikg Alright, I found the issue: https://github.com/vitejs/vite-ecosystem-ci/pull/42
Please have a look at it when you have time 👍

**Pull request merged**
